Hospital_Management/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('consultation.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/',include('userauth.urls')),
    path('dashboard',include('dashboard.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL,
     document_root=settings.MEDIA_ROOT)

consultation/urls.py
from django.urls import path
from consultation import views

app_name = "consultation"

urlpatterns = [
    path('',views.home,name='home'),
    path('make_appointment/<slug:dslug>',views.make_appointment,name='make_appointment'),
]

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = "dashboard"

urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard_home'),
]

userauth/urls.py
from django.urls import path
from . import views

app_name = 'userauth'

urlpatterns = [
    path('profile/',views.profile,name='account_profile'),
]

users/urls.py
from django.urls import path
from userauth import views
from allauth.socialaccount.views import ConnectionsView

urlpatterns = [
    path('accounts/social/connections/', ConnectionsView.as_view(), name='socialaccount_connections'),
]

consultation/models.py
from django.db import models

# Create your models here.
class Choice(models.Model):
    gender_choices = (
        ('M', 'Male'),
        ('F',"Female"),
        ('T','Transgender')
    )
class Status(models.Model):
    appoint_status = (
        ('Sc', 'Scheduled'),
        ('Co', 'Completed'),
        ('Ca', 'Cancelled')
    )



class Department(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, unique=True)
    def __str__(self):
        return self.name
    
class Healthcare_professional(models.Model):
    name = models.CharField(max_length=20)
    joining_date = models.DateField()
    phone = models.CharField(max_length=12,default='1234')
    email = models.CharField(max_length=40,blank=True,default='exapmple@gmail.com')
    class Meta:
        abstract = True
    def __str__(self):
        return self.name


class Doctor(Healthcare_professional):
    department = models.ForeignKey(Department,on_delete = models.CASCADE,default='medicine')
    availability = models.DurationField(default="")

class Nurse(Healthcare_professional):
    pass

class Pharmacist(Healthcare_professional):
    pass


class Patient(models.Model):
    name = models.CharField(max_length=20)
    photo = models.ImageField(upload_to='Patient/Photo',blank=True,null=True)
    gender = models.CharField(max_length=1, choices=Choice.gender_choices,default='Prefer Not to say')
    age = models.IntegerField(default=5,blank=True,null=True)
    patient_id = models.CharField(max_length=10,default="")
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE,blank=True,null=True)
    occupation = models.CharField(max_length=200,blank=True,null=True)
    address = models.CharField(max_length=1000,default = None,blank=True,null=True,unique=True)
    phone = models.CharField(max_length=14,default = '+91 12345678910',blank=True,null=True)
    email = models.CharField(max_length=40,blank=True,default='exapmple@gmail.com')
    def __str__(self):
        return self.name

class Appointment(models.Model):
    patient = models.ForeignKey(Patient,on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE,blank=True,null=True)
    date = models.DateField()
    time = models.TimeField(default='',blank=True,null=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE,blank=True,null=True)
    message = models.TextField(max_length=1000,default='')
    status = models.CharField(max_length=2, choices=Status.appoint_status, null=True,)
    def __str__(self):
        return f'{self.patient.name} - {self.date}'

dashboard/models.py
from django.db import models

# Create your models here.

userauth/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from allauth.account.forms import SignupForm
class CustomSignupForm(SignupForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

consultation/views.py
from django.shortcuts import render
from consultation.models import *
import uuid, datetime


# https://chatgpt.com/c/ae6bf9ec-a3e0-48f1-9f7e-7521885594a0
def patient_id_generator(gender):
    gender = gender[0]
    return f'{gender}-'
print(patient_id_generator('Male'))

# Create your views here.
def home(request):
    departments = Department.objects.all()
    return render(request,'home.html',{'depts':departments})


def make_appointment(request,dslug):
    departments = Department.objects.get(slug=dslug)  
    if request.method == "POST":
        name_input = request.POST.get('name')
        gender_input = 'Male'
        email_input = request.POST.get('email')
        date_input = request.POST.get('date')
        time_input = request.POST.get('time')
        dept_input = request.POST.get('department')
        phone_input = request.POST.get('phone')
        message_input = request.POST.get('message')
        try:
            dept = Department.objects.get(name=dept_input).id
        except: 
            pass
        finally:
            new_patient = Patient.objects.create(name=name_input,patient_id='M199811',email=email_input,phone=phone_input)
            new_patient.save()

            new_appointment = Appointment.objects.create(patient=new_patient,date=date_input,department="oncology",
                                                 message=message_input,time=time_input)
            new_appointment.save()
    context = {'depts':departments}
    return render(request,'book appointment.html',context)


dashboard/views.py
from django.shortcuts import render
from consultation.models import Appointment,Doctor,Nurse,Pharmacist,Patient
# Create your views here.
site_name = 'Health Center'
def dashboard(request):
    # Number of healthcare professionals present on a working day
    doctors = Doctor.objects.all().count
    nurses = Nurse.objects.all().count
    pharmacists = Pharmacist.objects.all().count
    patients = Patient.objects.all().count
    appoint = Appointment.objects.all()

    context = {
        'doctors':doctors,
        'nurses':nurses,
        'pharmacists':pharmacists,
        'patients':patients,
        'appoint':appoint,
        'name' :site_name
        }
    return render(request,"dashboard.html",context)

userauth/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request,'account/profile.html')

users/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% load allauth account %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Sign In" %}
    {% endelement %}
    {% if not SOCIALACCOUNT_ONLY %}
        {% setvar link %}
            <a href="{{ signup_url }}">
            {% endsetvar %}
            {% setvar end_link %}
            </a>
        {% endsetvar %}
        {% element p %}
            {% blocktranslate %}If you have not created an account yet, then please {{ link }}sign up{{ end_link }} first.{% endblocktranslate %}
        {% endelement %}
        {% url 'account_login' as login_url %}
        {% element form form=form method="post" action=login_url tags="entrance,login" %}
            {% slot body %}
                {% csrf_token %}
                {% element fields form=form unlabeled=True %}
                {% endelement %}
                {{ redirect_field }}
            {% endslot %}
            {% slot actions %}
                {% element button type="submit" tags="prominent,login" %}
                    {% trans "Sign In" %}
                {% endelement %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if LOGIN_BY_CODE_ENABLED or PASSKEY_LOGIN_ENABLED %}
        {% element hr %}
        {% endelement %}
        {% element button_group vertical=True %}
            {% if PASSKEY_LOGIN_ENABLED %}
                {% element button type="submit" form="mfa_login" id="passkey_login" tags="prominent,login,outline,primary" %}
                    {% trans "Sign in with a passkey" %}
                {% endelement %}
            {% endif %}
            {% if LOGIN_BY_CODE_ENABLED %}
                {% element button href=request_login_code_url tags="prominent,login,outline,primary" %}
                    {% trans "Mail me a sign-in code" %}
                {% endelement %}
            {% endif %}
        {% endelement %}
    {% endif %}
    {% if SOCIALACCOUNT_ENABLED %}
        {% include "socialaccount/snippets/login.html" with page_layout="entrance" %}
    {% endif %}
{% endblock content %}
{% block extra_body %}
    {{ block.super }}
    {% if PASSKEY_LOGIN_ENABLED %}
        {% include "mfa/webauthn/snippets/login_script.html" with button_id="passkey_login" %}
    {% endif %}
{% endblock %}

templates/appoint_confirmation.html
<h1>Hello</h1>

templates/book appointment.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<!-- MAKE AN APPOINTMENT -->
<section id="appointment" data-stellar-background-ratio="3">
     <div class="container">
          <div class="row">
               <div class="col-md-6 col-sm-6">         
                    
               </div>

               <div class="col-md-6 col-sm-6">
                    <!-- CONTACT FORM HERE -->
                    <form id="appointment-form" role="form" method="POST">
                         {% csrf_token %}
                         <!-- SECTION TITLE -->
                         <div class="section-title wow fadeInUp" data-wow-delay="0.4s">
                              <h2>Make an appointment {{name}}</h2>
                         </div>

                         <div class="wow fadeInUp" data-wow-delay="0.8s">
                              <div class="col-md-6 col-sm-6">
                                   <label for="name">Name</label>
                                   <input type="text" class="form-control" id="name" name="name" placeholder="Full Name" required>
                              </div>

                              <div class="col-md-6 col-sm-6">
                                   <label for="email">Email</label>
                                   <input type="email" class="form-control" id="email" name="email" placeholder="Your Email">
                              </div>

                              <div class="col-md-6 col-sm-6">
                                   <label for="date">Select Date</label>
                                   <input type="date" name="date" value="" class="form-control" required onchange="dateValidation()">
                              </div>

                              <div class="col-md-6 col-sm-6">
                                   <label for="time">Select Time</label>
                                   <input type="time" name="time"  class="form-control" required>
                             </div>

                              <div class="col-md-6 col-sm-6">
                                   <label for="select">Select Department</label>
                                   <select class="form-control">
                                        {% for i in depts %}
                                        <option name="department" required>{{i.name}}</option>
                                        {% endfor %}
                                   </select>
                              </div>

                              <div class="col-md-12 col-sm-12">
                                   <label for="telephone">Phone Number</label>
                                   <input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone" required maxlength="12" minlength="10">
                                   <label for="Message">Additional Message</label>
                                   <textarea class="form-control" rows="5" id="message" name="message" placeholder="Message"></textarea>
                                   <button type="submit" class="form-control" id="cf-submit" name="submit">Submit Button</button>
                              </div>
                         </div>
                   </form>
               </div>

          </div>
     </div>
</section>

<script>
     const date_input = document.getElementsById("date");
     const output = document.getElementsById("message");
     document.getElementById("message").innerHTML(date_input);
</script>
{% endblock %}

templates/dashboard.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    
    <!--dashboard css-->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    
    <!--Font awesome-->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'consultation:home'%}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'consultation:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->

    
    <!--first row-->
    <div class="row">
      <h3>Overview</h3>
      <!--Doctors-->
      <div class="col-md-2">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-stethoscope"></i>
            <h5 class="card-title">Doctors</h5>
            <p>{{doctors}}</p>
          </div>
        </div>
      </div>

      <!--Nurses-->
      <div class="col-md-2">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-user-nurse"></i>
            <h5 class="card-title">Nurses</h5>
            <p>{{nurses}}</p>
          </div>
        </div>
      </div>  

      <!--Pharmacists-->
      <div class="col-md-2">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-prescription-bottle-medical"></i>
            <h5 class="card-title">Pharmacists</h5>
            <p>{{pharmacists}}</p>
          </div>
        </div>
      </div>  

      <!--Patients-->
      <div class="col-md-2">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-bed"></i>
            <h5 class="card-title">Patients</h5>
            <p>{{patients}}</p>
          </div>
        </div>
      </div>

      <!--Appointments-->
      <div class="col-md-2">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-calendar-check"></i>
            <h5 class="card-title">Appointments</h5>
            <p>{{appoint}}</p>
          </div>
        </div>
      </div>

    </div>

    <!--Appointments-->
    <div class="row">
      <div class="row">
        <div class="col-md-4 border border-dark rounded 1">
          <h3>Doctors list</h3>

        </div>
        <div class="col-md-8 border border-dark rounded 1">
          <h3>Todays appointments</h3>
          {% for i in appoint %}
            <p>{{i.patient.name}} - {{i.date}} - {{i.department.name}}</p>
          {% endfor %}
        </div>
      </div>
    </div>
  





    

  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
     <title>Health - Medical Website Template</title>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="Tooplate">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/animate.css' %}">
     <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
     <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
     <!-- MAIN CSS -->
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <!--Font awesome-->
     <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
     <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
     <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

     <!-- SCRIPTS -->
     <script src="{% static 'js/form validation.js' %}"></script>
     <script src="{% static 'js/jquery.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
     <script src="{% static 'js/jquery.sticky.js' %}"></script>
     <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
     <script src="{% static 'js/wow.min.js' %}"></script>
     <script src="{% static 'js/smoothscroll.js' %}"></script>
     <script src="{% static 'js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'js/custom.js' %}"></script>
</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
     <!-- PRE LOADER -->
     <section class="preloader">
          <div class="spinner">
               <span class="spinner-rotate"></span>
          </div>
     </section>
     <!-- HEADER -->
     <header>
          <div class="container">
               <div class="row">
                    <div class="col-md-4 col-sm-5">
                         <p>Welcome to a Professional Health Care</p>
                    </div>
                    <div class="col-md-8 col-sm-7 text-align-right">
                         <span class="phone-icon"><i class="fa fa-phone"></i> 010-060-0160</span>
                         <span class="date-icon"><i class="fa fa-calendar-plus-o"></i> 6:00 AM - 10:00 PM (Mon-Fri)</span>
                         <span class="email-icon"><i class="fa fa-envelope-o"></i> <a href="#">info@healthcenter.com</a></span>
                    </div>
 
               </div>
          </div>
     </header>
 
 
     <!-- MENU -->
     <section class="navbar navbar-default navbar-static-top" role="navigation" style="background-color:var(--light_gray);">
          <div class="container">
 
               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>
 
                    <!-- lOGO TEXT HERE -->
                    <a href="{% url 'consultation:home' %}" class="navbar-brand"><i class="fa fa-h-square"></i>ealth Center</a>
               </div>
 
               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                         <li><a href="{% url 'consultation:home' %}" class="smoothScroll">Home</a></li>
                         {% if user.is_superuser %}
                         <li><a href="{% url 'dashboard:dashboard_home' %}" class="smoothScroll">Dashboard</a></li>
                         {% endif %}
                         <li><a href="#about" class="smoothScroll">About Us</a></li>
                         <li><a href="#team" class="smoothScroll">Doctors</a></li>
                         <li><a href="#google-map" class="smoothScroll">Contact</a></li>
                         {% if user.is_authenticated %}
                         <li class="dropdown"><a>Book Appointment</a>
                              <div class="content" style="border-color: aqua;">
                                   {% for i in depts %}
                                        <a href="{% url 'consultation:make_appointment' i.slug %}">{{i.name}}</a><br>
                                   {% endfor %}
                              </div>
                         </li>
                         <li class="dropdown"><a>Developer</a>
                         <li class="appointment-btn"><a href="{% url 'account_logout' %}" class="smoothScroll">Logout</a></li>
                         {% else %}
                         <!-- Drop down end-->
                         <li class="appointment-btn"><a href="{% url 'account_signup' %}">Signup</a></li>
                         <li class="appointment-btn"><a href="{% url 'account_login' %}">Signin</a></li>
                         {% endif %}
                    </ul>
               </div>
          </div>
     </section>
     {% block content %}
     {% endblock %}
     <!-- FOOTER -->
     <footer data-stellar-background-ratio="5" style="background-color: var(--light_gray);">
          <div class="container">
               <div class="row"> 
                    <div class="col-md-4 col-sm-4">
                         <div class="footer-thumb"> 
                              <h4 class="wow fadeInUp" data-wow-delay="0.4s">Contact Info</h4>
                              <p>Fusce at libero iaculis, venenatis augue quis, pharetra lorem. Curabitur ut dolor eu elit consequat ultricies.</p>
 
                              <div class="contact-info">
                                   <p><i class="fa fa-phone"></i> 010-070-0170</p>
                                   <p><i class="fa fa-envelope-o"></i> <a href="#">info@healthcenter.com</a></p>
                              </div>
                         </div>
                    </div>
                    <div class="col-md-4 col-sm-4"> 
                         <div class="footer-thumb">
                              <div class="opening-hours">
                                   <h4 class="wow fadeInUp" data-wow-delay="0.4s">Opening Hours</h4>
                                   <p>Monday - Friday <span>06:00 AM - 10:00 PM</span></p>
                                   <p>Saturday <span>09:00 AM - 08:00 PM</span></p>
                                   <p>Sunday <span>Closed</span></p>
                              </div> 
 
                              <ul class="social-icon">
                                   <li><a href="https://www.facebook.com/tooplate" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                                   <li><a href="#" class="fa fa-twitter"></a></li>
                                   <li><a href="#" class="fa fa-instagram"></a></li>
                              </ul>
                         </div>
                    </div>
                    <div class="col-md-12 col-sm-12 border-top">
                         <div class="col-md-4 col-sm-6">
                              <div class="copyright-text"> 
                                   <p>Copyright &copy; 2017 Health Center
                              </div>
                         </div>
                         <div class="col-md-6 col-sm-6">
                              <div class="footer-link"> 
                                   <a href="#">Laboratory Tests</a>
                                   <a href="#">Departments</a>
                                   <a href="#">Insurance Policy</a>
                                   <a href="#">Careers</a>
                              </div>
                         </div>
                         <div class="col-md-2 col-sm-2 text-align-center">
                              <div class="angle-up-btn"> 
                                  <a href="#top" class="smoothScroll wow fadeInUp" data-wow-delay="1.2s"><i class="fa fa-angle-up"></i></a>
                              </div>
                         </div>   
                    </div>
                    
               </div>
          </div>
     </footer>
 </body>
</html>